### ISSUE TITLE
Color with alpha support

### ISSUE THREAD

**Issue by vandenbrakel** [andrius-k/Toast#1]
When setting 

`Toast.GlobalAppearance.Color = UIColor.Black.ColorWithAlpha(0.6f); `

Alpha is ignored...

Tx.

**Comment by andrius-k** [comment]
Hi, thanks for reporting an issue.

I just tested it and it seems to be working fine. Could you please share more code on how you are presenting the toast? Also make sure to set global properties before actually showing a toast.

Regards

**Comment by andrius-k** [comment]
Hi,

could you please add some more details to explain your issue. It seems to be working fine for me. 
`Toast.GlobalAppearance.Color` is just a `UIColor` that I'm using to set the background color of container view, so it should work fine.

Regards

**Comment by vandenbrakel** [comment]
Hi. Let met test today. Will post the results.

**Comment by vandenbrakel** [comment]
This is the full method:

`
public void makeGlobalToast(string msg)
        {

            Toast.GlobalAppearance.Color = UIColor.Black.ColorWithAlpha(0.1f);
            Toast.MakeToast(msg)

                     .SetShowShadow(false)
                 .SetPosition(ToastPosition.Top)

                    .SetDuration(2000)

                    .Show();


        }

`

<img width="289" alt="screen shot 2018-05-12 at 11 06 28" src="https://user-images.githubusercontent.com/3436778/39955743-b21c0b4e-55d4-11e8-9342-1eb8cd08156a.png">

Result is without alpha...

**Comment by andrius-k** [comment]
Well, your exact code works perfectly for me. After all `UIColor.Black.ColorWithAlpha(0.1f);` returns just a `UIColor` that is later used to set background color of container view, so I don't see how it couldn't work.

Toast by default has some transparency. Could you please check if you see it? You would have to just present the toast without setting `Toast.GlobalAppearance.Color` at all. 

The only idea I have is that you might be calling `makeGlobalToast` method multiple times and many toasts are being presented covering each other. To test this could you please send the image of presented toast with `.SetShowShadow(true)` instead of `.SetShowShadow(false)`?

**Comment by andrius-k** [comment]
Hello,

If you still have this issue could you please make a minimal working example containing this bug and send me the project?

Regards

**Comment by vandenbrakel** [comment]
Sorry for the delay in answering. I figured it out today. I changed the alpha code in my global method. However the view I was testing still had a local implementation and thus not using my alpha code.

My bad. Thanks for answering.

**Comment by andrius-k** [comment]
No problem, glad that you issue was resolved!

Regards
