### ISSUE TITLE
Make protected constructor for Toast class

### ISSUE THREAD

**Issue by Time-To-Relax** [andrius-k/Toast#3]
Why constructor for Toast class is private? It is not impossible to create another toastview and override GetToastView method in Toast class

**Comment by andrius-k** [comment]
`Toast` is not a toast view. If you want to override `GetToastView` to use your new toast views you can totaly do that. You just need to inherit `baseToastView` or any other view from [here](https://github.com/andrius-k/Toast/tree/master/Toast/ToastViews) and return it from `GetToastView`. I should probably create a tutorial on how to do that at some point.

`Toast`s constructor is private because it is not supposed to be instantiated like that. Intention is to use builder methods like [this one](https://github.com/andrius-k/Toast/blob/master/Toast/Toast.cs#L57). Nothing wrong would happen if constructor would be public but I don't see any reason for doing that.

Did I understand your problem correctly?

**Comment by Time-To-Relax** [comment]
But I can't inherit GetToastView because Toast class has private constructor

**Comment by andrius-k** [comment]
You're right! You can't override `GetToastView` but you don't need to do that. You just use this `SetToastViewFactory` which you can find [here](https://github.com/andrius-k/Toast/blob/master/Toast/Toast.cs#L153). Just pass a `Func` returning your new toast view and you will be fine.

**Comment by andrius-k** [comment]
Is your problem solved now?

**Comment by andrius-k** [comment]
Closing assuming your problem is fixed.
